version: '3'
services:
  portainer:
    image: "portainer/portainer:arm"
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: portainer

  influxdb:
    image: "hypriot/rpi-influxdb:1.2.2"
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /var/influxdb:/data
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=smarthome
    container_name: influxdb

  grafana:
    image: "fg2it/grafana-armhf:v4.6.3"
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana

  rpi-433rc:
    image: "hazard/rpi-433rc:1.0.1"
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem
    ports:
      - "5555:5000"
    volumes:
      - ${CONFIG_DIR}/rpi-433rc/devices.json:/conf/devices.json:ro
    environment:
      - GPIO_OUT=17
      - CONFIG_DIR=/conf
      - MQTT_HOST=mqtt
      - MQTT_TOPIC=r433/{device_name}/switch
    links:
      - mqtt
    command: serve
    container_name: "rpi-433rc"

  pnp:
    image: "hazard/pnp:0.14.0-arm"
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem
    volumes:
      - ${CONFIG_DIR}/pnp/:/config
      - ${LOG_DIRECTORY}:/logs
    links:
      - mqtt
      - influxdb
    ports:
      - "9999:9999"
    environment:
      - ZWAY_USER=${ZWAY_USER}
      - ZWAY_PASSWORD=${ZWAY_PASSWORD}
      - INFLUX_PASSWORD=${INFLUX_PASSWORD}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    container_name: "pnp"

  mqtt:
    image: robotany/mosquitto-rpi
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./conf/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/mqtt/:/mosquitto/data
      - /var/log/mqtt:/mosquitto/log
    container_name: "mqtt"

  hass:
    image: homeassistant/raspberrypi3-homeassistant:0.88.1
    restart: unless-stopped
    network_mode: "host"
#    links:
#      - "mqtt:mqtt"
#      - "rpi-433rc:rpi-433rc"
#      - "influxdb:influxdb"
    ports:
      - "8123:8123"
      - "80:80"
    volumes:
      - /home/pi/configs/home-assistant-config:/config
    environment:
      - TZ=Europe/Berlin
    container_name: "hass"

  appdaemon:
    image: hazard/appdaemon-apps:0.3.2-arm
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ${CONFIG_DIR}/appdaemon:/apps
    environment:
      - TZ=Europe/Berlin
      - HA_URL=http://localhost:8123
      - HA_TOKEN=${HA_TOKEN}
    container_name: "appdaemon"
        
