version: '3'
services:
  portainer:
    image: "portainer/portainer:arm"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: portainer

  influxdb:
    image: "hypriot/rpi-influxdb:1.2.2"
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - /var/influxdb:/data
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=smarthome
    container_name: influxdb
  
  grafana:
    image: "fg2it/grafana-armhf:v4.6.3"
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana

  rpi-433rc:
    build: "https://github.com/HazardDede/rpi-433rc.git"
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem
    ports:
      - "5555:5000"
    volumes:
      - ${CONFIG_DIR}/rpi-433rc/devices.json:/conf/devices.json:ro
    environment:
      - GPIO_OUT=17
      - CONFIG_DIR=/conf
    restart: always
    command: serve
    container_name: "rpi-433rc"

  pnp:
    build:
      context: "https://github.com/HazardDede/pnp.git#v0.4.1"
      dockerfile: Dockerfile.arm32v7
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem
    volumes:
      - ${CONFIG_DIR}/pnp/config.json:/config/config.json:ro
    links:
      - mqtt
      - influxdb
    environment:
      - ZWAY_USER=${ZWAY_USER}
      - ZWAY_PASSWORD=${ZWAY_PASSWORD}
      - INFLUX_PASSWORD=${INFLUX_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: always
    container_name: "pnp"

  mqtt:
    image: robotany/mosquitto-rpi
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./conf/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/mqtt/:/mosquitto/data
      - /var/log/mqtt:/mosquitto/log
    container_name: "mqtt"

