version: '3'
services:
  portainer:
    image: "portainer/portainer:arm"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: portainer

  influxdb:
    image: "hypriot/rpi-influxdb:1.2.2"
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - /var/influxdb:/data
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=smarthome
    container_name: influxdb
  
  grafana:
    image: "fg2it/grafana-armhf:v4.6.3"
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana

  rpi-monitor:
    image: neoraptor/rpi-monitor:latest
    # restart: always
    ports:
      - "8888:8888"
      - "4200:4200"
    container_name: rpi-monitor
